name: Quarto Publish

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.32

      - name: Render site
        run: quarto render reports/

      - name: Publish to GitHub Pages
        run: |
          cd reports
          quarto publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
